/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ClienteMascota;
import Model.ClienteMascotaDAO;
import View.HistorialMedico;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author XPC
 */
public class DetalleExpediente extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    private int idCliente;
    private int idMascota;
    private String nombreMascota; // <-- nuevo

    private void mostrarDetalle(int idCliente, int idMascota) {
        ClienteMascotaDAO dao = new ClienteMascotaDAO();
        ClienteMascota cm = dao.obtenerDetalleExpediente(idCliente, idMascota);

        if (cm != null) {
            txtOutNombreCliente.setText(cm.getNombreCliente() + " " + cm.getApellidoCliente());
            txtOutTelefonoCliente.setText(cm.getTelefono());
            txtOutCorreoCliente.setText(cm.getEmail());
            txtOutDireccionCliente.setText(cm.getDireccion());
            txtOutNombreMascota.setText(cm.getNombreMascota());
            txtOutTipoMascota.setText(cm.getTipo());
            txtOutRazaMascota.setText(cm.getRaza());
            txtOutFechaNacimientoMascota.setText(cm.getFechaNacimiento().toString());
            txtOutPesoMascota.setText(cm.getPeso() + " kg");
            txtOutSexoMascota.setText(cm.getSexo());
        }
    }

    public DetalleExpediente(int idCliente, int idMascota) {
        initComponents();
                ///////////////////////NAVBAR///////////////////////
        //Accion del Boton de Ir a pantalla de Inicio
        navBtnInicio.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Inicio inicio = new Inicio();
                inicio.setVisible(true);
                setVisible(false);
            }
        });

        //Accion del Boton de Ir a pantalla de Expedientes
        navBtnExpedientes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Expedientes expediente = new Expedientes();
                expediente.setVisible(true);
                setVisible(false);

            }
        });

        //Accion del Boton de Ir a pantalla de Expedientes
        navBtnFacturar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Facturar facturar = new Facturar();
                facturar.setVisible(true);
                setVisible(false);

            }
        });

        //Accion del Boton de Ir a pantalla de Servicio
        navBtnServicios.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        ///////////////////////NAVBAR///////////////////////
        
        
        
        this.idCliente = idCliente;
        this.idMascota = idMascota;

        ClienteMascotaDAO dao = new ClienteMascotaDAO();
        ClienteMascota cm = dao.obtenerDetalleExpediente(idCliente, idMascota);

        nombreMascota = cm.getNombreMascota();
        txtOutNombreMascota.setText(nombreMascota);

        mostrarDetalle(idCliente, idMascota);

        btnHistorialMedico.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                HistorialMedico historial = new HistorialMedico(idMascota, nombreMascota);
                historial.setVisible(true);
                setVisible(false);
            }
        });

        //Regresar a ver todos los expedientes
        btnRegresarExpedientes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Expedientes expediente = new Expedientes();
                expediente.setVisible(true);
                setVisible(false);

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        navBtnInicio = new javax.swing.JButton();
        navBtnFacturar = new javax.swing.JButton();
        navBtnExpedientes = new javax.swing.JButton();
        navBtnServicios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOutNombreCliente = new javax.swing.JLabel();
        txtOutTelefonoCliente = new javax.swing.JLabel();
        txtOutCorreoCliente = new javax.swing.JLabel();
        txtOutDireccionCliente = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtOutNombreMascota = new javax.swing.JLabel();
        txtOutTipoMascota = new javax.swing.JLabel();
        txtOutRazaMascota = new javax.swing.JLabel();
        txtOutFechaNacimientoMascota = new javax.swing.JLabel();
        txtOutPesoMascota = new javax.swing.JLabel();
        txtOutSexoMascota = new javax.swing.JLabel();
        btnHistorialMedico = new javax.swing.JButton();
        btnRegresarExpedientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dra.Huellitas");
        setBackground(new java.awt.Color(143, 206, 255));

        jPanel2.setBackground(new java.awt.Color(24, 114, 184));
        jPanel2.setPreferredSize(new java.awt.Dimension(960, 110));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Veterinaria Dra.Huellitas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        navBtnInicio.setBackground(new java.awt.Color(255, 255, 255));
        navBtnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        navBtnInicio.setForeground(new java.awt.Color(0, 0, 0));
        navBtnInicio.setText("Inicio");
        navBtnInicio.setBorder(null);
        navBtnInicio.setMaximumSize(new java.awt.Dimension(102, 27));
        navBtnInicio.setMinimumSize(new java.awt.Dimension(102, 27));
        navBtnInicio.setPreferredSize(new java.awt.Dimension(102, 27));
        navBtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBtnInicioActionPerformed(evt);
            }
        });

        navBtnFacturar.setBackground(new java.awt.Color(255, 255, 255));
        navBtnFacturar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        navBtnFacturar.setForeground(new java.awt.Color(0, 0, 0));
        navBtnFacturar.setText("Facturar");
        navBtnFacturar.setBorder(null);
        navBtnFacturar.setMaximumSize(new java.awt.Dimension(102, 27));
        navBtnFacturar.setMinimumSize(new java.awt.Dimension(102, 27));
        navBtnFacturar.setPreferredSize(new java.awt.Dimension(102, 27));
        navBtnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBtnFacturarActionPerformed(evt);
            }
        });

        navBtnExpedientes.setBackground(new java.awt.Color(255, 255, 255));
        navBtnExpedientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        navBtnExpedientes.setForeground(new java.awt.Color(0, 0, 0));
        navBtnExpedientes.setText("Expedientes");
        navBtnExpedientes.setBorder(null);
        navBtnExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBtnExpedientesActionPerformed(evt);
            }
        });

        navBtnServicios.setBackground(new java.awt.Color(255, 255, 255));
        navBtnServicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        navBtnServicios.setForeground(new java.awt.Color(0, 0, 0));
        navBtnServicios.setText("Servicios");
        navBtnServicios.setBorder(null);
        navBtnServicios.setMaximumSize(new java.awt.Dimension(102, 27));
        navBtnServicios.setMinimumSize(new java.awt.Dimension(102, 27));
        navBtnServicios.setPreferredSize(new java.awt.Dimension(102, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(navBtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(navBtnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(navBtnExpedientes)
                .addGap(89, 89, 89)
                .addComponent(navBtnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navBtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navBtnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navBtnExpedientes)
                    .addComponent(navBtnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Propietario");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Telefono:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Correo:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Dirección:");

        txtOutNombreCliente.setText("...");

        txtOutTelefonoCliente.setText("...");

        txtOutCorreoCliente.setText("...");

        txtOutDireccionCliente.setText("...");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutNombreCliente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutCorreoCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutTelefonoCliente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutDireccionCliente)))
                .addGap(233, 233, 233))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(313, 313, 313))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOutNombreCliente)
                    .addComponent(jLabel4)
                    .addComponent(txtOutTelefonoCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOutCorreoCliente)
                    .addComponent(txtOutDireccionCliente)
                    .addComponent(jLabel7))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mascota");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nombre:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tipo:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Raza:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Fecha de Nacimiento:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Peso:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Sexo:");

        txtOutNombreMascota.setText("...");

        txtOutTipoMascota.setText("...");

        txtOutRazaMascota.setText("...");

        txtOutFechaNacimientoMascota.setText("...");

        txtOutPesoMascota.setText("...");

        txtOutSexoMascota.setText("...");

        btnHistorialMedico.setText("Historial Medico");
        btnHistorialMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(329, 329, 329))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOutNombreMascota))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOutRazaMascota)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtOutFechaNacimientoMascota)
                                    .addGap(143, 143, 143))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(btnHistorialMedico)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtOutPesoMascota))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtOutSexoMascota)))
                                .addGap(256, 256, 256))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutTipoMascota)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(txtOutNombreMascota)
                    .addComponent(txtOutFechaNacimientoMascota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtOutTipoMascota)
                    .addComponent(txtOutPesoMascota)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtOutRazaMascota)
                    .addComponent(jLabel13)
                    .addComponent(txtOutSexoMascota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistorialMedico)
                .addGap(20, 20, 20))
        );

        btnRegresarExpedientes.setText("<- Regresar");
        btnRegresarExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarExpedientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresarExpedientes)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresarExpedientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navBtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBtnInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navBtnInicioActionPerformed

    private void navBtnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBtnFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navBtnFacturarActionPerformed

    private void navBtnExpedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBtnExpedientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navBtnExpedientesActionPerformed

    private void btnHistorialMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialMedicoActionPerformed

    private void btnRegresarExpedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarExpedientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarExpedientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorialMedico;
    private javax.swing.JButton btnRegresarExpedientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton navBtnExpedientes;
    private javax.swing.JButton navBtnFacturar;
    private javax.swing.JButton navBtnInicio;
    private javax.swing.JButton navBtnServicios;
    private javax.swing.JLabel txtOutCorreoCliente;
    private javax.swing.JLabel txtOutDireccionCliente;
    private javax.swing.JLabel txtOutFechaNacimientoMascota;
    private javax.swing.JLabel txtOutNombreCliente;
    private javax.swing.JLabel txtOutNombreMascota;
    private javax.swing.JLabel txtOutPesoMascota;
    private javax.swing.JLabel txtOutRazaMascota;
    private javax.swing.JLabel txtOutSexoMascota;
    private javax.swing.JLabel txtOutTelefonoCliente;
    private javax.swing.JLabel txtOutTipoMascota;
    // End of variables declaration//GEN-END:variables
}
