/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.FacturaDAO;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author XPC
 */
public class Facturar extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Facturar() throws SQLException {
        initComponents();
        
        FacturaDAO dao = new FacturaDAO();
        
        comboBoxMPago.removeAllItems();  // Limpia todos los ítems existentes
        comboBoxIDFactura.removeAllItems();  // Limpia todos los ítems existentes                
        
        //opciones de método de pago
        List<String> metodos = dao.obtenerMetodosPago();
        for (String metodo : metodos) {
            comboBoxMPago.addItem(metodo);
        }
        
        //ids de factura
        List<Integer> ids = dao.obtenerIdsFactura();
        for (Integer id : ids) {
            comboBoxIDFactura.addItem(id.toString());
        }
        
        //mostrar el monto total
        comboBoxIDFactura.addActionListener(e -> {
            try {
                if (comboBoxIDFactura.getSelectedItem() != null) {
                    int idFactura = Integer.parseInt(comboBoxIDFactura.getSelectedItem().toString());
                    double monto = dao.obtenerMontoFactura(idFactura); // usa el procedimiento
                    txtMontoTotal.setText(String.valueOf(monto));
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }   
        });
        
        btnFacturar.addActionListener(e -> {
            try {
                if (comboBoxIDFactura.getSelectedItem() != null && !txtMontoTotal.getText().isEmpty()) {
                    int idFactura = Integer.parseInt(comboBoxIDFactura.getSelectedItem().toString());
                    double monto = Double.parseDouble(txtMontoTotal.getText());
                    
                    String seleccionado = comboBoxMPago.getSelectedItem().toString();
                    int idMetodoPago = Integer.parseInt(seleccionado.split(" - ")[0].trim());
                                        
                    dao.actualizarMontoFactura(idFactura, monto, idMetodoPago);

                    javax.swing.JOptionPane.showMessageDialog(this, "Factura actualizada correctamente.");
                    txtMontoTotal.setText("");
                }
            } catch (Exception ex) {
                if (ex.getMessage().contains("ORA-20001")){
                    javax.swing.JOptionPane.showMessageDialog(this,"La factura ya está cancelada.");
                } else {                                                                       
                    ex.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar la factura: " + ex.getMessage());
                }
            }
        });        
    }
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxMPago = new javax.swing.JComboBox<>();
        mPago = new javax.swing.JLabel();
        btnFacturar = new javax.swing.JButton();
        comboBoxIDFactura = new javax.swing.JComboBox<>();
        idsFactura = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        montoACancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dra.Huellitas");
        setBackground(new java.awt.Color(143, 206, 255));

        jPanel2.setBackground(new java.awt.Color(24, 114, 184));
        jPanel2.setPreferredSize(new java.awt.Dimension(960, 110));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Veterinaria Dra.Huellitas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        comboBoxMPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mPago.setText("Método de Pago");

        btnFacturar.setText("Facturar");

        comboBoxIDFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        idsFactura.setText("Seleccionar ID Factura");

        montoACancelar.setText("Monto a Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mPago, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(comboBoxMPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idsFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxIDFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(404, 404, 404))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFacturar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(montoACancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mPago))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montoACancelar))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxIDFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idsFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFacturar)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacturar;
    private javax.swing.JComboBox<String> comboBoxIDFactura;
    private javax.swing.JComboBox<String> comboBoxMPago;
    private javax.swing.JLabel idsFactura;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mPago;
    private javax.swing.JLabel montoACancelar;
    private javax.swing.JTextField txtMontoTotal;
    // End of variables declaration//GEN-END:variables

 
}
